module fp_add (
    input  [31:0] a,
    input  [31:0] b,
    output reg [31:0] result
);

    /*
     * IEEE-754 single-precision floating-point adder.
     *
     * Supported:
     *   - Normal numbers
     *   - Subnormal numbers
     *   - +0 / -0
     *   - +Inf / -Inf
     *   - NaN
     *   - Round-to-nearest-even
     *   - Guard / Round / Sticky bits
     *   - Overflow to infinity
     *   - Underflow to subnormal / zero
     *
     * No exception/status flags are generated.
     */

    reg        sign_a;
    reg        sign_b;

    reg [7:0]  exp_a;
    reg [7:0]  exp_b;

    reg [22:0] frac_a;
    reg [22:0] frac_b;

    reg [23:0] mant_a;
    reg [23:0] mant_b;

    /*
     * Effective exponents.
     *
     * Subnormal numbers use effective exponent 1 for
     * alignment, while retaining a zero hidden bit.
     */
    reg [7:0] exp_a_eff;
    reg [7:0] exp_b_eff;

    reg        sign_large;
    reg [7:0]  exp_large;

    /*
     * Extended significand:
     *
     * [26:3] = 24-bit significand
     * [2]    = Guard
     * [1]    = Round
     * [0]    = Sticky
     */
    reg [26:0] mant_large_ext;
    reg [26:0] mant_small_ext;

    reg [27:0] mant_sum_ext;
    reg [26:0] mant_diff_ext;

    /*
     * Working significand after add/subtract and normalization.
     */
    reg [26:0] mant_work;

    /*
     * 25-bit temporary for rounding.
     *
     * [23:0] = rounded significand
     * [24]    = carry generated by rounding
     */
    reg [24:0] mant_rounded_ext;

    reg [7:0] exp_result;
    reg       sign_result;

    reg       round_up;

    integer shift_count;
    integer shift_amount;


    /*
     * Right shift with sticky-bit generation.
     *
     * All bits discarded by the shift are ORed into bit 0.
     *
     * The function is called only from exponent-alignment paths,
     * where amount is guaranteed to be > 0.
     */
    function automatic [26:0] shift_right_sticky;
        input [26:0] value;
        input integer amount;

        reg sticky;
        integer i;

        begin

            /*
             * Large shift:
             *
             * All 27 bits are discarded. The result is zero
             * except for the sticky bit.
             */
            if (amount >= 27) begin

                sticky = 1'b0;

                for (i = 0; i < 27; i = i + 1) begin

                    if (value[i])
                        sticky = 1'b1;

                end

                shift_right_sticky = 27'd0;
                shift_right_sticky[0] = sticky;

            end

            /*
             * Normal right shift with sticky-bit generation.
             */
            else begin

                sticky = 1'b0;

                for (i = 0; i < 27; i = i + 1) begin

                    if (i < amount) begin

                        if (value[i])
                            sticky = 1'b1;

                    end

                end

                shift_right_sticky = value >> amount;

                if (sticky)
                    shift_right_sticky[0] = 1'b1;

            end

        end

    endfunction


    always @(*) begin

        /*
         * Default result.
         */
        result = 32'h00000000;

        /*
         * Decode operands.
         */
        sign_a = a[31];
        sign_b = b[31];

        exp_a = a[30:23];
        exp_b = b[30:23];

        frac_a = a[22:0];
        frac_b = b[22:0];


        /*
         * =========================================================
         * SPECIAL VALUES
         * =========================================================
         */

        /*
         * NaN.
         */
        if ((exp_a == 8'hFF) && (frac_a != 23'd0)) begin

            result = 32'h7FC00000;

        end
        else if ((exp_b == 8'hFF) && (frac_b != 23'd0)) begin

            result = 32'h7FC00000;

        end

        /*
         * Infinity + Infinity.
         */
        else if ((exp_a == 8'hFF) &&
                 (frac_a == 23'd0) &&
                 (exp_b == 8'hFF) &&
                 (frac_b == 23'd0)) begin

            /*
             * +Inf + -Inf = NaN
             */
            if (sign_a != sign_b)
                result = 32'h7FC00000;
            else
                result = {sign_a, 8'hFF, 23'd0};

        end

        /*
         * One operand is infinity.
         */
        else if ((exp_a == 8'hFF) &&
                 (frac_a == 23'd0)) begin

            result = {sign_a, 8'hFF, 23'd0};

        end
        else if ((exp_b == 8'hFF) &&
                 (frac_b == 23'd0)) begin

            result = {sign_b, 8'hFF, 23'd0};

        end


        /*
         * =========================================================
         * ZERO HANDLING
         * =========================================================
         */

        /*
         * Both operands are zero.
         *
         * Round-to-nearest-even:
         *
         *   +0 + +0 = +0
         *   +0 + -0 = +0
         *   -0 + +0 = +0
         *   -0 + -0 = -0
         */
        else if ((exp_a == 8'd0) &&
                 (frac_a == 23'd0) &&
                 (exp_b == 8'd0) &&
                 (frac_b == 23'd0)) begin

            result = {
                sign_a & sign_b,
                31'd0
            };

        end

        /*
         * a = zero.
         */
        else if ((exp_a == 8'd0) &&
                 (frac_a == 23'd0)) begin

            result = b;

        end

        /*
         * b = zero.
         */
        else if ((exp_b == 8'd0) &&
                 (frac_b == 23'd0)) begin

            result = a;

        end


        /*
         * =========================================================
         * FINITE NON-ZERO OPERANDS
         * =========================================================
         */
        else begin

            /*
             * Build significands.
             *
             * Normal:
             *     1.frac
             *
             * Subnormal:
             *     0.frac
             */
            if (exp_a == 8'd0)
                mant_a = {1'b0, frac_a};
            else
                mant_a = {1'b1, frac_a};

            if (exp_b == 8'd0)
                mant_b = {1'b0, frac_b};
            else
                mant_b = {1'b1, frac_b};


            /*
             * Effective exponent.
             *
             * Subnormal encoded exponent 0 is treated as exponent 1
             * for alignment.
             */
            if (exp_a == 8'd0)
                exp_a_eff = 8'd1;
            else
                exp_a_eff = exp_a;

            if (exp_b == 8'd0)
                exp_b_eff = 8'd1;
            else
                exp_b_eff = exp_b;


            /*
             * =====================================================
             * ALIGNMENT
             * =====================================================
             */

            mant_large_ext = 27'd0;
            mant_small_ext = 27'd0;

            /*
             * a has larger exponent.
             */
            if (exp_a_eff > exp_b_eff) begin

                exp_large  = exp_a_eff;
                sign_large = sign_a;

                mant_large_ext[26:3] = mant_a;
                mant_small_ext[26:3] = mant_b;

                shift_amount =
                    exp_a_eff - exp_b_eff;

                mant_small_ext =
                    shift_right_sticky(
                        mant_small_ext,
                        shift_amount
                    );

            end

            /*
             * b has larger exponent.
             */
            else if (exp_b_eff > exp_a_eff) begin

                exp_large  = exp_b_eff;
                sign_large = sign_b;

                mant_large_ext[26:3] = mant_b;
                mant_small_ext[26:3] = mant_a;

                shift_amount =
                    exp_b_eff - exp_a_eff;

                mant_small_ext =
                    shift_right_sticky(
                        mant_small_ext,
                        shift_amount
                    );

            end

            /*
             * Same exponent: compare significands.
             */
            else if (mant_a >= mant_b) begin

                exp_large  = exp_a_eff;
                sign_large = sign_a;

                mant_large_ext[26:3] = mant_a;
                mant_small_ext[26:3] = mant_b;

            end

            else begin

                exp_large  = exp_b_eff;
                sign_large = sign_b;

                mant_large_ext[26:3] = mant_b;
                mant_small_ext[26:3] = mant_a;

            end


            /*
             * =====================================================
             * SAME SIGN -> ADDITION
             * =====================================================
             */
            if (sign_a == sign_b) begin

                mant_sum_ext =
                    {1'b0, mant_large_ext} +
                    {1'b0, mant_small_ext};

                exp_result  = exp_large;
                sign_result = sign_large;

                /*
                 * Addition produced:
                 *
                 * 10.xxxxx
                 *
                 * Shift right by one and increment exponent.
                 */
                if (mant_sum_ext[27]) begin

                    mant_work = mant_sum_ext[27:1];

                    /*
                     * Preserve discarded bit as sticky.
                     */
                    if (mant_sum_ext[0])
                        mant_work[0] = 1'b1;

                    exp_result = exp_large + 8'd1;

                end
                else begin

                    mant_work = mant_sum_ext[26:0];

                end

            end


            /*
             * =====================================================
             * DIFFERENT SIGNS -> SUBTRACTION
             * =====================================================
             */
            else begin

                /*
                 * Exact cancellation.
                 */
                if (mant_large_ext == mant_small_ext) begin

                    /*
                     * Exact zero under round-to-nearest-even.
                     */
                    result = 32'h00000000;

                end
                else begin

                    mant_diff_ext =
                        mant_large_ext -
                        mant_small_ext;

                    mant_work  = mant_diff_ext;
                    exp_result = exp_large;
                    sign_result = sign_large;


                    /*
                     * =================================================
                     * NORMALIZATION
                     * =================================================
                     *
                     * Shift left until hidden bit becomes 1.
                     *
                     * Stop at exponent = 1.
                     *
                     * If exponent = 1 and hidden bit remains 0,
                     * result is subnormal.
                     */
                    for (shift_count = 0;
                         shift_count < 26;
                         shift_count = shift_count + 1) begin

                        if ((mant_work[26] == 1'b0) &&
                            (exp_result > 8'd1)) begin

                            mant_work =
                                mant_work << 1;

                            exp_result =
                                exp_result - 8'd1;

                        end

                    end

                end

            end


            /*
             * =====================================================
             * ROUNDING
             * =====================================================
             *
             * Only execute if subtraction did not produce
             * exact cancellation.
             */
            if ((sign_a == sign_b) ||
                (mant_large_ext != mant_small_ext)) begin

                /*
                 * Round-to-nearest-even.
                 *
                 * G = bit 2
                 * R = bit 1
                 * S = bit 0
                 *
                 * Increment when:
                 *
                 *     G && (R || S || LSB)
                 */
                round_up =
                    mant_work[2] &&
                    (
                        mant_work[1] ||
                        mant_work[0] ||
                        mant_work[3]
                    );


                /*
                 * Extend to 25 bits before adding rounding increment.
                 *
                 * This is the critical v2 fix.
                 */
                mant_rounded_ext = {
                    1'b0,
                    mant_work[26:3]
                };

                if (round_up)
                    mant_rounded_ext =
                        mant_rounded_ext + 25'd1;


                /*
                 * =================================================
                 * ROUNDING CARRY
                 * =================================================
                 *
                 * Example:
                 *
                 *     1.111111... -> 10.000000...
                 *
                 * The carry is represented by bit 24.
                 */
                if (mant_rounded_ext[24]) begin

                    /*
                     * Shift the rounded significand right by one.
                     *
                     * After rounding:
                     *
                     *     10.xxxxx
                     *
                     * becomes:
                     *
                     *     1.0xxxxx
                     */
                    mant_rounded_ext =
                        mant_rounded_ext >> 1;

                    exp_result =
                        exp_result + 8'd1;

                end


                /*
                 * =================================================
                 * OVERFLOW
                 * =================================================
                 *
                 * Exponent 255 is reserved for Inf/NaN.
                 */
                if (exp_result >= 8'hFF) begin

                    result = {
                        sign_result,
                        8'hFF,
                        23'd0
                    };

                end

                /*
                 * =================================================
                 * SUBNORMAL / UNDERFLOW
                 * =================================================
                 */
                else if ((exp_result == 8'd1) &&
                         (mant_rounded_ext[23] == 1'b0)) begin

                    /*
                     * No implicit leading 1.
                     */
                    result = {
                        sign_result,
                        8'd0,
                        mant_rounded_ext[22:0]
                    };

                end

                /*
                 * =================================================
                 * NORMAL RESULT
                 * =================================================
                 */
                else begin

                    result = {
                        sign_result,
                        exp_result,
                        mant_rounded_ext[22:0]
                    };

                end

            end

        end

    end

endmodule