`ifndef CPU_SCOREBOARD_SV
`define CPU_SCOREBOARD_SV

`include "uvm_macros.svh"

package cpu_scoreboard_pkg;

    import uvm_pkg::*;
    import cpu_pkg::*;
    import cpu_model_pkg::*;

    // ------------------------------------------------------------
    // Two independent analysis implementations:
    //
    //   expected  -> original stimulus transaction
    //   observed  -> final architectural state from monitor
    //
    // The expected transaction is executed by the reference model
    // before comparison.
    // ------------------------------------------------------------

    `uvm_analysis_imp_decl(_expected)
    `uvm_analysis_imp_decl(_observed)

    // ------------------------------------------------------------
    // CPU UVM Scoreboard
    //
    // Architectural checking:
    //
    //   PC
    //   Integer registers x0-x31
    //   Data memory 0-255
    //
    // The scoreboard does NOT access the DUT hierarchy.
    // ------------------------------------------------------------

    class cpu_scoreboard extends uvm_scoreboard;

        `uvm_component_utils(cpu_scoreboard)

        // --------------------------------------------------------
        // Analysis inputs
        // --------------------------------------------------------

        uvm_analysis_imp_expected #(cpu_transaction, cpu_scoreboard)
            expected_export;

        uvm_analysis_imp_observed #(cpu_transaction, cpu_scoreboard)
            observed_export;

        // --------------------------------------------------------
        // Reference model
        // --------------------------------------------------------

        cpu_reference_model ref_model;

        // --------------------------------------------------------
        // Pending expected / observed transactions
        //
        // Expected transactions are generated from stimulus and
        // converted to architectural predictions.
        //
        // Observed transactions are generated by the monitor.
        // --------------------------------------------------------

        cpu_transaction expected_queue[$];
        cpu_transaction observed_queue[$];

        // --------------------------------------------------------
        // Statistics
        // --------------------------------------------------------

        int unsigned num_expected;
        int unsigned num_observed;
        int unsigned num_matches;
        int unsigned num_mismatches;

        // --------------------------------------------------------
        // Constructor
        // --------------------------------------------------------

        function new(
            string name = "cpu_scoreboard",
            uvm_component parent = null
        );

            super.new(name, parent);

            expected_export =
                new("expected_export", this);

            observed_export =
                new("observed_export", this);

            ref_model =
                new();

            num_expected  = 0;
            num_observed  = 0;
            num_matches   = 0;
            num_mismatches = 0;

        endfunction

        // --------------------------------------------------------
        // Build phase
        // --------------------------------------------------------

        function void build_phase(uvm_phase phase);

            super.build_phase(phase);

            `uvm_info(
                "CPU_SCOREBOARD",
                "CPU architectural scoreboard constructed",
                UVM_LOW
            )

        endfunction

        // --------------------------------------------------------
        // Predict architectural state
        //
        // The input transaction contains:
        //
        //   instr_mem
        //   init_int_regs
        //   instr_count
        //
        // The reference model produces:
        //
        //   regs[]
        //   data_mem[]
        //   pc
        // --------------------------------------------------------

        function cpu_transaction
            predict_transaction(
                cpu_transaction stimulus
            );

            cpu_transaction predicted;

            int i;

            predicted =
                cpu_transaction::type_id::create(
                    "predicted_transaction"
                );

            // ----------------------------------------------------
            // Execute stimulus using independent reference model.
            // ----------------------------------------------------

            ref_model.execute_program(
                stimulus.instr_mem,
                stimulus.init_int_regs,
                stimulus.instr_count
            );

            // ----------------------------------------------------
            // Copy stimulus metadata.
            // ----------------------------------------------------

            predicted.instr_count = stimulus.instr_count;

            for (i = 0; i < 64; i++) begin
                predicted.instr_mem[i] =
                    stimulus.instr_mem[i];
            end

            for (i = 0; i < 32; i++) begin
                predicted.init_int_regs[i] =
                    stimulus.init_int_regs[i];
            end

            // ----------------------------------------------------
            // Copy expected architectural PC.
            // ----------------------------------------------------

            predicted.expected_pc =
                ref_model.pc;

            // ----------------------------------------------------
            // Copy expected integer registers.
            // ----------------------------------------------------

            for (i = 0; i < 32; i++) begin

                predicted.exp_int_regs[i] =
                    ref_model.regs[i];

            end

            // ----------------------------------------------------
            // Copy expected data memory.
            // ----------------------------------------------------

            for (i = 0; i < 256; i++) begin

                predicted.exp_mem[i] =
                    ref_model.data_mem[i];

            end

            return predicted;

        endfunction

        // --------------------------------------------------------
        // Compare PC
        // --------------------------------------------------------

        function bit compare_pc(
            cpu_transaction expected,
            cpu_transaction observed
        );

            if (expected.expected_pc !== observed.observed_pc) begin

                `uvm_error(
                    "CPU_PC_MISMATCH",
                    $sformatf(
                        "PC mismatch: expected=%08h observed=%08h",
                        expected.expected_pc,
                        observed.observed_pc
                    )
                )

                return 1'b0;

            end

            return 1'b1;

        endfunction

        // --------------------------------------------------------
        // Compare integer registers
        // --------------------------------------------------------

        function bit compare_registers(
            cpu_transaction expected,
            cpu_transaction observed
        );

            bit pass;
            int i;

            pass = 1'b1;

            for (i = 0; i < 32; i++) begin

                if (expected.exp_int_regs[i] !==
                    observed.observed_int_regs[i]) begin

                    `uvm_error(
                        "CPU_REG_MISMATCH",
                        $sformatf(
                            "Register x%0d mismatch: expected=%08h observed=%08h",
                            i,
                            expected.exp_int_regs[i],
                            observed.observed_int_regs[i]
                        )
                    )

                    pass = 1'b0;

                end

            end

            return pass;

        endfunction

        // --------------------------------------------------------
        // Compare data memory
        //
        // Compare all 256 locations because the architectural
        // memory abstraction is 256 words.
        // --------------------------------------------------------

        function bit compare_memory(
            cpu_transaction expected,
            cpu_transaction observed
        );

            bit pass;
            int i;

            pass = 1'b1;

            for (i = 0; i < 256; i++) begin

                if (expected.exp_mem[i] !==
                    observed.observed_mem[i]) begin

                    `uvm_error(
                        "CPU_MEM_MISMATCH",
                        $sformatf(
                            "Memory[%0d] mismatch: expected=%08h observed=%08h",
                            i,
                            expected.exp_mem[i],
                            observed.observed_mem[i]
                        )
                    )

                    pass = 1'b0;

                end

            end

            return pass;

        endfunction

        // --------------------------------------------------------
        // Compare complete architectural state
        // --------------------------------------------------------

        function void compare_transactions(
            cpu_transaction expected,
            cpu_transaction observed
        );

            bit pass_pc;
            bit pass_regs;
            bit pass_mem;

            pass_pc =
                compare_pc(
                    expected,
                    observed
                );

            pass_regs =
                compare_registers(
                    expected,
                    observed
                );

            pass_mem =
                compare_memory(
                    expected,
                    observed
                );

            if (pass_pc && pass_regs && pass_mem) begin

                num_matches++;

                `uvm_info(
                    "CPU_SCOREBOARD",
                    $sformatf(
                        "PASS: architectural state matches. PC=%08h",
                        observed.observed_pc
                    ),
                    UVM_MEDIUM
                )

            end
            else begin

                num_mismatches++;

                `uvm_error(
                    "CPU_SCOREBOARD",
                    "FAIL: architectural state mismatch detected"
                )

            end

        endfunction

        // --------------------------------------------------------
        // Expected transaction analysis callback
        //
        // Called by the predictor/driver connection.
        // --------------------------------------------------------

        function void write_expected(
            cpu_transaction stimulus
        );

            cpu_transaction predicted;

            num_expected++;

            `uvm_info(
                "CPU_SCOREBOARD",
                $sformatf(
                    "Received expected stimulus: instr_count=%0d",
                    stimulus.instr_count
                ),
                UVM_MEDIUM
            )

            // ----------------------------------------------------
            // Run independent reference model.
            // ----------------------------------------------------

            predicted =
                predict_transaction(stimulus);

            // ----------------------------------------------------
            // Queue predicted architectural state.
            // ----------------------------------------------------

            expected_queue.push_back(predicted);

            // ----------------------------------------------------
            // If monitor result is already waiting, compare now.
            // ----------------------------------------------------

            try_compare();

        endfunction

        // --------------------------------------------------------
        // Observed transaction analysis callback
        //
        // Called by cpu_monitor.analysis_port.
        // --------------------------------------------------------

        function void write_observed(
            cpu_transaction observed
        );

            num_observed++;

            `uvm_info(
                "CPU_SCOREBOARD",
                $sformatf(
                    "Received observed state: PC=%08h",
                    observed.observed_pc
                ),
                UVM_MEDIUM
            )

            observed_queue.push_back(observed);

            // ----------------------------------------------------
            // If expected result is already waiting, compare now.
            // ----------------------------------------------------

            try_compare();

        endfunction

        // --------------------------------------------------------
        // Pair expected and observed transactions
        // --------------------------------------------------------

        function void try_compare();

            cpu_transaction expected;
            cpu_transaction observed;

            while ((expected_queue.size() > 0) &&
                   (observed_queue.size() > 0)) begin

                expected =
                    expected_queue.pop_front();

                observed =
                    observed_queue.pop_front();

                compare_transactions(
                    expected,
                    observed
                );

            end

        endfunction

        // --------------------------------------------------------
        // Check phase
        //
        // Detect transactions that never received a corresponding
        // transaction from the other side.
        // --------------------------------------------------------

        function void check_phase(uvm_phase phase);

            super.check_phase(phase);

            // ----------------------------------------------------
            // Attempt final pairing.
            // ----------------------------------------------------

            try_compare();

            // ----------------------------------------------------
            // Missing expected transactions.
            // ----------------------------------------------------

            if (expected_queue.size() != 0) begin

                `uvm_error(
                    "CPU_SB_MISSING_OBS",
                    $sformatf(
                        "%0d expected transaction(s) have no observed transaction",
                        expected_queue.size()
                    )
                )

            end

            // ----------------------------------------------------
            // Missing observed transactions.
            // ----------------------------------------------------

            if (observed_queue.size() != 0) begin

                `uvm_error(
                    "CPU_SB_MISSING_EXP",
                    $sformatf(
                        "%0d observed transaction(s) have no expected transaction",
                        observed_queue.size()
                    )
                )

            end

        endfunction

        // --------------------------------------------------------
        // Report phase
        // --------------------------------------------------------

        function void report_phase(uvm_phase phase);

            super.report_phase(phase);

            `uvm_info(
                "CPU_SCOREBOARD",
                "==============================================",
                UVM_NONE
            )

            `uvm_info(
                "CPU_SCOREBOARD",
                "CPU ARCHITECTURAL SCOREBOARD SUMMARY",
                UVM_NONE
            )

            `uvm_info(
                "CPU_SCOREBOARD",
                $sformatf(
                    "Expected transactions : %0d",
                    num_expected
                ),
                UVM_NONE
            )

            `uvm_info(
                "CPU_SCOREBOARD",
                $sformatf(
                    "Observed transactions : %0d",
                    num_observed
                ),
                UVM_NONE
            )

            `uvm_info(
                "CPU_SCOREBOARD",
                $sformatf(
                    "Matches               : %0d",
                    num_matches
                ),
                UVM_NONE
            )

            `uvm_info(
                "CPU_SCOREBOARD",
                $sformatf(
                    "Mismatches            : %0d",
                    num_mismatches
                ),
                UVM_NONE
            )

            `uvm_info(
                "CPU_SCOREBOARD",
                "==============================================",
                UVM_NONE
            )

            if (num_mismatches != 0) begin

                `uvm_error(
                    "CPU_SCOREBOARD",
                    "Architectural verification FAILED"
                )

            end
            else if ((num_expected != 0) &&
                     (num_expected == num_observed)) begin

                `uvm_info(
                    "CPU_SCOREBOARD",
                    "Architectural verification PASSED",
                    UVM_NONE
                )

            end
            else begin

                `uvm_warning(
                    "CPU_SCOREBOARD",
                    "No complete scoreboard comparison was performed"
                )

            end

        endfunction

    endclass

endpackage

`endif